---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Cluster and SGs'

Parameters:

  Project:
    Description: Project code the resources should be associated with.
    Type: String
    Default: 'CP'
  VpcId:
    Type: String
    Description: >
      Optional - Specifies the ID of an existing VPC in which to launch
      your container instances. If you specify a VPC ID, you must specify a list of
      existing subnets in that VPC. If you do not specify a VPC ID, a new VPC is created
      with atleast 1 subnet.
  SubnetIds:
    Type: List<String>
    Description: >
      Specifies the Comma separated list of existing VPC Subnet
  ClusterName:
    Description: The cluster name to be created.
    Type: String
  EKSVersion:
    Type: String
    Default: '1.15'
  Environment:
    Description: Environment the resources should be associated with.
    Type: String
    Default: 'dev'
    AllowedValues: [ 'dev', 'test', 'uat', 'prod' ]

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    DependsOn:
      - EKSServiceRole
      - ControlPlaneSecurityGroup
    Properties:
      Name: !Ref ClusterName
      Version: !Ref EKSVersion
      RoleArn: !GetAtt EKSServiceRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds: !Ref SubnetIds

  EKSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Project}-eksServiceRole-${AWS::Region}-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: [eks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${Project}-eks-cluster-security-group-${Environment}
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VpcId

Outputs:
  SecurityGroups:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !Ref ControlPlaneSecurityGroup
    Export:
      Name: !Sub ${Project}-EKS-ControlPlaneSecurityGroup-${Environment}
